In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.ndim

1

In [6]:
a.size

5

In [7]:
a.itemsize

4

In [8]:
a[0]

1

In [9]:
a[-1]

5

In [10]:
a[-5]

1

In [11]:
a=np.array([2,3,4,5],dtype=float)
a

array([2., 3., 4., 5.])

In [12]:
type(a)

numpy.ndarray

In [13]:
#we can use dtype int,float,str

In [17]:
a=np.array([2,5,1,6.7,7,8])

In [18]:
a

array([2. , 5. , 1. , 6.7, 7. , 8. ])

In [22]:
a=np.array([2,5,1,6.7,7,"abc",8])
a

array(['2', '5', '1', '6.7', '7', 'abc', '8'], dtype='<U32')

In [23]:
a=np.array([2,5,1,6.7,7,8,"abc"],dtype=int)
a #we cant convert into str to int

ValueError: invalid literal for int() with base 10: 'abc'

In [24]:
#creating 1dim numpy array

In [25]:
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [27]:
a=np.arange(5,100,5)
a

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [33]:
a=np.arange(2,6,0.6)
a

array([2. , 2.6, 3.2, 3.8, 4.4, 5. , 5.6])

In [34]:
a=np.linspace(2,5,7) ##2 is start 5 is last 7 is no of elements
a

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [35]:
a=np.linspace(3,8)
a

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [36]:
a=np.logspace(2,5,3)
a

array([   100.        ,   3162.27766017, 100000.        ])

In [38]:
a=np.logspace(7,12,23)
a

array([1.00000000e+07, 1.68761248e+07, 2.84803587e+07, 4.80638086e+07,
       8.11130831e+07, 1.36887451e+08, 2.31012970e+08, 3.89860370e+08,
       6.57933225e+08, 1.11033632e+09, 1.87381742e+09, 3.16227766e+09,
       5.33669923e+09, 9.00628020e+09, 1.51991108e+10, 2.56502091e+10,
       4.32876128e+10, 7.30527154e+10, 1.23284674e+11, 2.08056754e+11,
       3.51119173e+11, 5.92553098e+11, 1.00000000e+12])

In [39]:
a=np.zeros(5)
a ##by default it is float,we can use int,complex,str

array([0., 0., 0., 0., 0.])

In [40]:
a=np.zeros(5,dtype=int)
a


array([0, 0, 0, 0, 0])

In [42]:
a=np.ones(5,dtype=int)
a

array([1, 1, 1, 1, 1])

In [43]:
#array,arange,linspace,zeros,ones are methods

In [45]:
a=np.random.randint(4,7)
a ##it will give one random element

6

In [46]:
a=np.random.randint(2,78,69)
a

array([11, 51, 54, 66, 17, 37, 73, 65, 52, 47, 77, 40, 16, 63, 42, 32, 21,
       13, 62, 10, 74, 25, 35, 55,  4, 29, 28, 47, 74, 22, 33, 57, 67, 16,
       24, 57, 69, 65,  7, 57, 59, 27, 30, 46, 34, 21,  2, 20,  9,  8, 56,
       22, 48, 76, 58, 43, 59, 33, 44, 22, 53,  7, 68, 66, 64,  7, 14,  3,
       18])

In [47]:
a=np.random.rand(5)
a #it generates random elemnts from 0

array([0.46544389, 0.19253748, 0.76598962, 0.06833197, 0.41935508])

In [48]:
#collection of 1d is called 2d array

In [62]:
a=np.array([[11,22,33,44],[1,2,3,4]])
a

array([[11, 22, 33, 44],
       [ 1,  2,  3,  4]])

In [63]:
type(a)

numpy.ndarray

In [64]:
a.ndim

2

In [65]:
a[0][1]

22

In [66]:
#a[r,c] accessing
a[1][::-3]

array([4, 1])

In [67]:
a[0:2,1:3:1]

array([[22, 33],
       [ 2,  3]])

In [68]:
#reshape is used 
a=np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [69]:
a.reshape(5,6) #6 row 5 col or 10 row 3 col is only possible 30 elements

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [74]:
a=np.random.randint(45,size=20).reshape(5,4)
a

array([[19, 33, 22, 12],
       [32, 23, 23, 27],
       [ 6, 16, 34, 27],
       [19,  4,  7, 12],
       [12,  3,  1, 16]])

In [75]:
a.reshape(5,4)


array([[19, 33, 22, 12],
       [32, 23, 23, 27],
       [ 6, 16, 34, 27],
       [19,  4,  7, 12],
       [12,  3,  1, 16]])

In [78]:
a[1:4:1,1:3:1]

array([[23, 23],
       [16, 34],
       [ 4,  7]])

In [82]:
a[0:5:4,0:4:3]

array([[19, 12],
       [12, 16]])

In [90]:
a[1:4:2,0:3:2]

array([[32, 23],
       [19,  7]])